### PR TITLE
Unaligned PCI BAR address fix

### LINKED ISSUE #12: libsel4vmmplatsupport: unaligned PCI BAR address (x86, PCI pass-through)
Hi,

I think I may have found a bug in `vmm_pci_helper_map_bars` from `libsel4vmmplatsupport/src/arch/x86/drivers/vmm_pci_helpers.c`.

The PCI interface standard mandates that BAR addresses be naturally aligned, i.e. the address must be a multiple of the size. This is a requirement for the weird BAR size probing logic (save value, write 0xffffffff, read back size mask, restore value) to function properly. The `vmm_pci_helper_map_bars` function however calls `vm_reserve_anon_memory` to reserve memory in the guest space and this function does not (necessarily) returns naturally aligned addresses.

I ran into this using `qemu`. Simple CAmkES setup with a single Linux VM, with PCI pass-throughs for both a `virtio-net` and a `e1000` network interfaces. At boot, the PCI bus is correctly scanned as such:
```
lib_pci_scan_dev found pci device 0 0
PCI :: 00.00.00 : intel Unknown device ID. (vid 0x8086 did 0x29c0) line0 pin0
lib_pci_scan_dev found pci device 0 1
PCI :: 00.01.00 : Unknown vendor ID. Unknown device ID. (vid 0x1234 did 0x1111) line0 pin0
    BAR0 : [ mem 0xfd000000 sz 0x1000000 szmask 0xff000000  prefetch ]
    BAR2 : [ mem 0xfebf0000 sz 0x1000 szmask 0xfffff000   ]
lib_pci_scan_dev found pci device 0 2
PCI :: 00.02.00 : Unknown vendor ID. Unknown device ID. (vid 0x1af4 did 0x1000) line11 pin1
    BAR0 : [ io 0xc080 sz 0x20 szmask 0xffffffe0 ]
    BAR1 : [ mem 0xfebf1000 sz 0x1000 szmask 0xfffff000   ]
    BAR4 : [ mem 0xfe000000 sz 0x4000 szmask 0xffffc000 64bit prefetch ]             /* size: 0x4000 */
lib_pci_scan_dev found pci device 0 3
PCI :: 00.03.00 : intel Unknown device ID. (vid 0x8086 did 0x100e) line11 pin1
    BAR0 : [ mem 0xfebc0000 sz 0x20000 szmask 0xfffe0000   ]                         /* size: 0x20000 */
    BAR1 : [ io 0xc000 sz 0x40 szmask 0xffffffc0 ]
lib_pci_scan_dev found pci device 0 31
PCI :: 00.1f.00 : intel intel_ich9_8 (vid 0x8086 did 0x2918) line0 pin0
lib_pci_scan_dev found multi function device 0 31
PCI :: 00.1f.02 : intel Unknown device ID. (vid 0x8086 did 0x2922) line10 pin1
    BAR4 : [ io 0xc0a0 sz 0x20 szmask 0xffffffe0 ]
    BAR5 : [ mem 0xfebf2000 sz 0x1000 szmask 0xfffff000   ]
PCI :: 00.1f.03 : intel intel_ich9_6 (vid 0x8086 did 0x2930) line10 pin1
    BAR4 : [ io 0x700 sz 0x40 szmask 0xffffffc0 ]
```

The issue shows up with BAR4 of PCI device 00.02.00 (virtio-net) as well as BAR0 of PCI device 00.03.00 which have sizes larger than one page. Here's what the guest Linux kernel finds:

```
[    0.190000] pci 0000:00:00.0: [5e14:0042] type 00 class 0x060000
[    0.190000] pci 0000:00:01.0: [1af4:1000] type 00 class 0x020000
[    0.200000] pci 0000:00:01.0: reg 0x10: [io  0xc080-0xc09f]
[    0.210000] pci 0000:00:01.0: reg 0x14: [mem 0x18001000-0x18001fff]
[    0.210000] pci 0000:00:01.0: reg 0x18: [mem 0x18002000-0x18003fff pref]          /* size: 0x2000 ! */
[    0.220000] pci 0000:00:02.0: [8086:100e] type 00 class 0x020000
[    0.230000] pci 0000:00:02.0: reg 0x10: [mem 0x18006000-0x18007fff]               /* size: 0x2000 ! */
[    0.230000] pci 0000:00:02.0: reg 0x14: [io  0xc000-0xc03f]
```

The address 0x18002000 is not legal to store a BAR of size 0x4000 (0x18002000 & (0x4000 - 1) != 0). Likewise address 0x18006000 is not legal to store a BAR of size 0x20000 (0x18006000 & (0x20000 - 1) != 0).

### PR DESCRIPTION
**Pull request by maaaat**
These two commits fix #12. I'm not very familiar with this code base, I hope I'm not breaking more than I'm fixing here.

In particular this PR changes the prototype of `vm_reserve_anon_memory` to add a requested address alignment. For backward compatibility an alternative could be to add a new variant of this function, say `vm_reserve_anon_memory_aligned`, and have `vm_reserve_anon_memory` call `vm_reserve_anon_memory_aligned` with a requested alignment of one page. I'd happily do so if you think it's better.

### CODE REVIEW

File: libsel4vm/src/guest_memory.c [hunk 1]
```diff
@@ -394,13 +395,13 @@ vm_memory_reservation_t *vm_reserve_anon_memory(vm_t *vm, size_t size,
...
 
-    allocable_region = find_allocable_anon_region(vm, ROUND_UP(size, BIT(seL4_PageBits)));
+    allocable_region = find_allocable_anon_region(vm, ROUND_UP(size, BIT(seL4_PageBits)), align);
     if (!allocable_region) {
         ZF_LOGE("Failed to reserve anon memory: No anonymous memory available to cater reservation size");
         return NULL;
     }
 
-    reservation_addr = allocable_region->alloc_addr;
+    reservation_addr = ROUND_UP(allocable_region->alloc_addr, (uintptr_t) align);
```
Comment (WellMcGarnicle) [inline libsel4vm/src/guest_memory.c:404]: I think you will also will need to update line 426 from
`allocable_region->alloc_addr += ROUND_UP(size, BIT(seL4_PageBits))` 
to
`allocable_region->alloc_addr = reservation_addr + ROUND_UP(size, BIT(seL4_PageBits))`
To make sure the next sub-allocation in this anon region won't overlap with your current aligned allocation 
_(Sorry Github doesn't seem to allow me to comment on the actual line)_

**Review by WellMcGarnicle — COMMENTED** [review]
Thanks for finding and fixing this bug! Awesome fix :+1: 
Just a small comment about setting the next allocation address in the region

File: libsel4vm/src/guest_memory.c (hunk 1 above)
Comment (maaaat) [reply libsel4vm/src/guest_memory.c:404]: Oh wow, absolutely, I totally overlooked this important detail. Thanks for that, I added your suggestion verbatim and force-pushed the branch.

**Review by WellMcGarnicle — APPROVED** [review]
LGTM, thanks for adding the fix!

@oliver-wm Can you review and run the ssrg tests? (don't think I have the ability to)

**Comment by lsf37** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by ssrg-bamboo** [comment]
All the tests we ran have passed! Nice job!

**Comment by ssrg-bamboo** [comment]
## Test results for commit e9d91310c01ea5cbd41eb5a80503339de503e774

### Summary

#### NOTE: some test results have been updated!

| Test name | Result |
| --- | --- |
| Code Quality - Check licenses - seL4_projects_libs - EXT-maaaat-unaligned-PCI-BAR-address-fix-13 | FAILED |
| Code Quality - Style - seL4_projects_libs - EXT-maaaat-unaligned-PCI-BAR-address-fix-13 | SUCCESSFUL |
| Code Quality - Style - seL4_projects_libs - EXT-maaaat-unaligned-PCI-BAR-address-fix-13 1 | SUCCESSFUL |

### Detailed failure logs

| Project | Stage | Result summary |
| --- | --- | --- |
| Code Quality - Check licenses - seL4_projects_libs - EXT-maaaat-unaligned-PCI-BAR-address-fix-13 | Check licenses | 1 of 1 job failed |

**Job: lic**
Build logs

    13-Jan-2021 04:27:15	Build Code Quality - Check licenses - seL4_projects_libs - EXT-maaaat-unaligned-PCI-BAR-address-fix-13 - lic #1 (CQ-SEL4PROJECTSLIBSCL42-SEL4PROJECTSLIBSLICCQ-1) started building on agent A local agent 2, bamboo version: 7.1.4
    13-Jan-2021 04:27:15	I run on the Bamboo server!
    13-Jan-2021 04:27:15	Build working directory is /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-SEL4PROJECTSLIBSCL42-SEL4PROJECTSLIBSLICCQ
    13-Jan-2021 04:27:15	Executing build Code Quality - Check licenses - seL4_projects_libs - EXT-maaaat-unaligned-PCI-BAR-address-fix-13 - lic #1 (CQ-SEL4PROJECTSLIBSCL42-SEL4PROJECTSLIBSLICCQ-1)
    13-Jan-2021 04:27:15	Preparing artifact 'code' for use at /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-SEL4PROJECTSLIBSCL42-SEL4PROJECTSLIBSLICCQ/. (location: .)
    13-Jan-2021 04:27:15	Artifact 'code' prepared in 16.78 ms at /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-SEL4PROJECTSLIBSCL42-SEL4PROJECTSLIBSLICCQ/./code.tar.gz
    13-Jan-2021 04:27:15	Running pre-build action: VCS Version Collector
    13-Jan-2021 04:27:15	Starting task 'Untar code' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    13-Jan-2021 04:27:15	+ tar xf code.tar.gz --recursive-unlink
    13-Jan-2021 04:27:15	Finished task 'Untar code' with result: Success
    13-Jan-2021 04:27:15	Starting task 'Set permissions so Bamboo can cleanup' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    13-Jan-2021 04:27:15	+ chmod -R o+rwx /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-SEL4PROJECTSLIBSCL42-SEL4PROJECTSLIBSLICCQ
    13-Jan-2021 04:27:15	Finished task 'Set permissions so Bamboo can cleanup' with result: Success
    13-Jan-2021 04:27:15	Starting task 'Check license' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    13-Jan-2021 04:27:15	+ python license-tool/check_license.py seL4_projects_libs
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/.gitignore: seL4_projects_libs/.gitignore: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/CMakeLists.txt: seL4_projects_libs/CMakeLists.txt: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/Findsel4_projects_libs.cmake: seL4_projects_libs/Findsel4_projects_libs.cmake: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/LICENSE.md: seL4_projects_libs/LICENSE.md: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/README.md: seL4_projects_libs/README.md: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/.github/CODE_OF_CONDUCT.md: seL4_projects_libs/.github/CODE_OF_CONDUCT.md: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/.github/CONTRIBUTING.md: seL4_projects_libs/.github/CONTRIBUTING.md: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/.github/workflows/pr.yml: seL4_projects_libs/.github/workflows/pr.yml: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/.github/workflows/push.yml: seL4_projects_libs/.github/workflows/push.yml: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4bga/CMakeLists.txt: seL4_projects_libs/libsel4bga/CMakeLists.txt: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4bga/README.md: seL4_projects_libs/libsel4bga/README.md: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4bga/arch_include/x86/bga/bga.h: seL4_projects_libs/libsel4bga/arch_include/x86/bga/bga.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4bga/src/arch-x86/bga.c: seL4_projects_libs/libsel4bga/src/arch-x86/bga.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4dma/CMakeLists.txt: seL4_projects_libs/libsel4dma/CMakeLists.txt: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4dma/include/dma/dma.h: seL4_projects_libs/libsel4dma/include/dma/dma.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4dma/src/dma.c: seL4_projects_libs/libsel4dma/src/dma.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4keyboard/CMakeLists.txt: seL4_projects_libs/libsel4keyboard/CMakeLists.txt: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4keyboard/README.md: seL4_projects_libs/libsel4keyboard/README.md: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4keyboard/arch_include/x86/keyboard/keyboard.h: seL4_projects_libs/libsel4keyboard/arch_include/x86/keyboard/keyboard.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4keyboard/include/keyboard/codes.h: seL4_projects_libs/libsel4keyboard/include/keyboard/codes.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4keyboard/src/codes.c: seL4_projects_libs/libsel4keyboard/src/codes.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4keyboard/src/arch-x86/keyboard.c: seL4_projects_libs/libsel4keyboard/src/arch-x86/keyboard.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4nanopb/CMakeLists.txt: seL4_projects_libs/libsel4nanopb/CMakeLists.txt: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4nanopb/README.md: seL4_projects_libs/libsel4nanopb/README.md: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4nanopb/include/sel4nanopb/sel4nanopb.h: seL4_projects_libs/libsel4nanopb/include/sel4nanopb/sel4nanopb.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4nanopb/src/common.c: seL4_projects_libs/libsel4nanopb/src/common.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4rpc/CMakeLists.txt: seL4_projects_libs/libsel4rpc/CMakeLists.txt: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4rpc/README.md: seL4_projects_libs/libsel4rpc/README.md: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4rpc/rpc.proto: seL4_projects_libs/libsel4rpc/rpc.proto: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4rpc/include/sel4rpc/client.h: seL4_projects_libs/libsel4rpc/include/sel4rpc/client.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4rpc/include/sel4rpc/server.h: seL4_projects_libs/libsel4rpc/include/sel4rpc/server.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4rpc/src/client.c: seL4_projects_libs/libsel4rpc/src/client.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4rpc/src/server.c: seL4_projects_libs/libsel4rpc/src/server.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vchan/CMakeLists.txt: seL4_projects_libs/libsel4vchan/CMakeLists.txt: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vchan/include/linuxsel4vchan/sel4libvchan.h: seL4_projects_libs/libsel4vchan/include/linuxsel4vchan/sel4libvchan.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vchan/include/linuxsel4vchan/vmm_driver.h: seL4_projects_libs/libsel4vchan/include/linuxsel4vchan/vmm_driver.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vchan/include/sel4vchan/libvchan.h: seL4_projects_libs/libsel4vchan/include/sel4vchan/libvchan.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vchan/include/sel4vchan/vchan_component.h: seL4_projects_libs/libsel4vchan/include/sel4vchan/vchan_component.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vchan/include/sel4vchan/vchan_copy.h: seL4_projects_libs/libsel4vchan/include/sel4vchan/vchan_copy.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vchan/include/sel4vchan/vchan_sharemem.h: seL4_projects_libs/libsel4vchan/include/sel4vchan/vchan_sharemem.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vchan/include/sel4vchan/vmm_manager.h: seL4_projects_libs/libsel4vchan/include/sel4vchan/vmm_manager.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vchan/src/vchan_component.c: seL4_projects_libs/libsel4vchan/src/vchan_component.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/CMakeLists.txt: seL4_projects_libs/libsel4vm/CMakeLists.txt: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/README.md: seL4_projects_libs/libsel4vm/README.md: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/arch_include/arm/sel4vm/arch/guest_arm_context.h: seL4_projects_libs/libsel4vm/arch_include/arm/sel4vm/arch/guest_arm_context.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/arch_include/arm/sel4vm/arch/guest_memory_arch.h: seL4_projects_libs/libsel4vm/arch_include/arm/sel4vm/arch/guest_memory_arch.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/arch_include/arm/sel4vm/arch/guest_vm_arch.h: seL4_projects_libs/libsel4vm/arch_include/arm/sel4vm/arch/guest_vm_arch.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/arch_include/arm/sel4vm/arch/processor.h: seL4_projects_libs/libsel4vm/arch_include/arm/sel4vm/arch/processor.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/arch_include/x86/sel4vm/arch/guest_memory_arch.h: seL4_projects_libs/libsel4vm/arch_include/x86/sel4vm/arch/guest_memory_arch.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/arch_include/x86/sel4vm/arch/guest_vm_arch.h: seL4_projects_libs/libsel4vm/arch_include/x86/sel4vm/arch/guest_vm_arch.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/arch_include/x86/sel4vm/arch/guest_x86_context.h: seL4_projects_libs/libsel4vm/arch_include/x86/sel4vm/arch/guest_x86_context.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/arch_include/x86/sel4vm/arch/ioports.h: seL4_projects_libs/libsel4vm/arch_include/x86/sel4vm/arch/ioports.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/arch_include/x86/sel4vm/arch/vmcall.h: seL4_projects_libs/libsel4vm/arch_include/x86/sel4vm/arch/vmcall.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/arch_include/x86/sel4vm/arch/vmcs_fields.h: seL4_projects_libs/libsel4vm/arch_include/x86/sel4vm/arch/vmcs_fields.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/arch_include/x86/sel4vm/arch/vmexit_reasons.h: seL4_projects_libs/libsel4vm/arch_include/x86/sel4vm/arch/vmexit_reasons.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/docs/README.md: seL4_projects_libs/libsel4vm/docs/README.md: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/docs/libsel4vm_arm_guest_vm.md: seL4_projects_libs/libsel4vm/docs/libsel4vm_arm_guest_vm.md: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/docs/libsel4vm_boot.md: seL4_projects_libs/libsel4vm/docs/libsel4vm_boot.md: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/docs/libsel4vm_guest_arm_context.md: seL4_projects_libs/libsel4vm/docs/libsel4vm_guest_arm_context.md: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/docs/libsel4vm_guest_iospace.md: seL4_projects_libs/libsel4vm/docs/libsel4vm_guest_iospace.md: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/docs/libsel4vm_guest_irq_controller.md: seL4_projects_libs/libsel4vm/docs/libsel4vm_guest_irq_controller.md: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/docs/libsel4vm_guest_memory.md: seL4_projects_libs/libsel4vm/docs/libsel4vm_guest_memory.md: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/docs/libsel4vm_guest_memory_helpers.md: seL4_projects_libs/libsel4vm/docs/libsel4vm_guest_memory_helpers.md: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/docs/libsel4vm_guest_ram.md: seL4_projects_libs/libsel4vm/docs/libsel4vm_guest_ram.md: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/docs/libsel4vm_guest_vcpu_fault.md: seL4_projects_libs/libsel4vm/docs/libsel4vm_guest_vcpu_fault.md: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/docs/libsel4vm_guest_vm.md: seL4_projects_libs/libsel4vm/docs/libsel4vm_guest_vm.md: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/docs/libsel4vm_guest_vm_util.md: seL4_projects_libs/libsel4vm/docs/libsel4vm_guest_vm_util.md: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/docs/libsel4vm_guest_x86_context.md: seL4_projects_libs/libsel4vm/docs/libsel4vm_guest_x86_context.md: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/docs/libsel4vm_x86_guest_vm.md: seL4_projects_libs/libsel4vm/docs/libsel4vm_x86_guest_vm.md: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/docs/libsel4vm_x86_ioports.md: seL4_projects_libs/libsel4vm/docs/libsel4vm_x86_ioports.md: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/docs/libsel4vm_x86_vmcall.md: seL4_projects_libs/libsel4vm/docs/libsel4vm_x86_vmcall.md: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/include/sel4vm/boot.h: seL4_projects_libs/libsel4vm/include/sel4vm/boot.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/include/sel4vm/guest_iospace.h: seL4_projects_libs/libsel4vm/include/sel4vm/guest_iospace.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/include/sel4vm/guest_irq_controller.h: seL4_projects_libs/libsel4vm/include/sel4vm/guest_irq_controller.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/include/sel4vm/guest_memory.h: seL4_projects_libs/libsel4vm/include/sel4vm/guest_memory.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/include/sel4vm/guest_memory_helpers.h: seL4_projects_libs/libsel4vm/include/sel4vm/guest_memory_helpers.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/include/sel4vm/guest_ram.h: seL4_projects_libs/libsel4vm/include/sel4vm/guest_ram.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/include/sel4vm/guest_vcpu_fault.h: seL4_projects_libs/libsel4vm/include/sel4vm/guest_vcpu_fault.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/include/sel4vm/guest_vm.h: seL4_projects_libs/libsel4vm/include/sel4vm/guest_vm.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/include/sel4vm/guest_vm_exits.h: seL4_projects_libs/libsel4vm/include/sel4vm/guest_vm_exits.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/include/sel4vm/guest_vm_util.h: seL4_projects_libs/libsel4vm/include/sel4vm/guest_vm_util.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/sel4_arch_include/aarch64/sel4vm/sel4_arch/processor.h: seL4_projects_libs/libsel4vm/sel4_arch_include/aarch64/sel4vm/sel4_arch/processor.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/sel4_arch_include/arm_hyp/sel4vm/sel4_arch/processor.h: seL4_projects_libs/libsel4vm/sel4_arch_include/arm_hyp/sel4vm/sel4_arch/processor.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/src/boot.c: seL4_projects_libs/libsel4vm/src/boot.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/src/guest_memory.c: seL4_projects_libs/libsel4vm/src/guest_memory.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/src/guest_memory.h: seL4_projects_libs/libsel4vm/src/guest_memory.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/src/guest_memory_helpers.c: seL4_projects_libs/libsel4vm/src/guest_memory_helpers.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/src/guest_ram.c: seL4_projects_libs/libsel4vm/src/guest_ram.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/src/guest_vcpu_fault.c: seL4_projects_libs/libsel4vm/src/guest_vcpu_fault.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/src/guest_vspace.c: seL4_projects_libs/libsel4vm/src/guest_vspace.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/src/guest_vspace.h: seL4_projects_libs/libsel4vm/src/guest_vspace.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/src/vm.c: seL4_projects_libs/libsel4vm/src/vm.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/src/vm.h: seL4_projects_libs/libsel4vm/src/vm.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/src/vm_boot.h: seL4_projects_libs/libsel4vm/src/vm_boot.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/src/arch/arm/arm_vm.h: seL4_projects_libs/libsel4vm/src/arch/arm/arm_vm.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/src/arch/arm/arm_vm_exits.h: seL4_projects_libs/libsel4vm/src/arch/arm/arm_vm_exits.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/src/arch/arm/boot.c: seL4_projects_libs/libsel4vm/src/arch/arm/boot.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/src/arch/arm/fault.c: seL4_projects_libs/libsel4vm/src/arch/arm/fault.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/src/arch/arm/fault.h: seL4_projects_libs/libsel4vm/src/arch/arm/fault.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/src/arch/arm/guest_arm_context.c: seL4_projects_libs/libsel4vm/src/arch/arm/guest_arm_context.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/src/arch/arm/guest_irq_controller.c: seL4_projects_libs/libsel4vm/src/arch/arm/guest_irq_controller.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/src/arch/arm/guest_memory_arch.c: seL4_projects_libs/libsel4vm/src/arch/arm/guest_memory_arch.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/src/arch/arm/guest_vcpu_fault_arch.c: seL4_projects_libs/libsel4vm/src/arch/arm/guest_vcpu_fault_arch.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/src/arch/arm/guest_vspace_arch.h: seL4_projects_libs/libsel4vm/src/arch/arm/guest_vspace_arch.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/src/arch/arm/mem_abort.c: seL4_projects_libs/libsel4vm/src/arch/arm/mem_abort.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/src/arch/arm/mem_abort.h: seL4_projects_libs/libsel4vm/src/arch/arm/mem_abort.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/src/arch/arm/syscalls.c: seL4_projects_libs/libsel4vm/src/arch/arm/syscalls.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/src/arch/arm/syscalls.h: seL4_projects_libs/libsel4vm/src/arch/arm/syscalls.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/src/arch/arm/vm.c: seL4_projects_libs/libsel4vm/src/arch/arm/vm.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/src/arch/arm/vgic/vgic.c: seL4_projects_libs/libsel4vm/src/arch/arm/vgic/vgic.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/src/arch/arm/vgic/vgic.h: seL4_projects_libs/libsel4vm/src/arch/arm/vgic/vgic.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/src/arch/arm/vgic/vgicv2_defs.h: seL4_projects_libs/libsel4vm/src/arch/arm/vgic/vgicv2_defs.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/src/arch/x86/boot.c: seL4_projects_libs/libsel4vm/src/arch/x86/boot.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/src/arch/x86/debug.c: seL4_projects_libs/libsel4vm/src/arch/x86/debug.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/src/arch/x86/debug.h: seL4_projects_libs/libsel4vm/src/arch/x86/debug.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/src/arch/x86/ept.c: seL4_projects_libs/libsel4vm/src/arch/x86/ept.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/src/arch/x86/guest_irq_controller.c: seL4_projects_libs/libsel4vm/src/arch/x86/guest_irq_controller.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/src/arch/x86/guest_state.h: seL4_projects_libs/libsel4vm/src/arch/x86/guest_state.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/src/arch/x86/guest_vcpu_fault_arch.c: seL4_projects_libs/libsel4vm/src/arch/x86/guest_vcpu_fault_arch.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/src/arch/x86/guest_vspace_arch.h: seL4_projects_libs/libsel4vm/src/arch/x86/guest_vspace_arch.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/src/arch/x86/guest_x86_context.c: seL4_projects_libs/libsel4vm/src/arch/x86/guest_x86_context.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/src/arch/x86/halt.c: seL4_projects_libs/libsel4vm/src/arch/x86/halt.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/src/arch/x86/interrupt.c: seL4_projects_libs/libsel4vm/src/arch/x86/interrupt.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/src/arch/x86/interrupt.h: seL4_projects_libs/libsel4vm/src/arch/x86/interrupt.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/src/arch/x86/ioports.c: seL4_projects_libs/libsel4vm/src/arch/x86/ioports.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/src/arch/x86/vm.c: seL4_projects_libs/libsel4vm/src/arch/x86/vm.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/src/arch/x86/vmcall.c: seL4_projects_libs/libsel4vm/src/arch/x86/vmcall.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/src/arch/x86/vmcs.c: seL4_projects_libs/libsel4vm/src/arch/x86/vmcs.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/src/arch/x86/vmcs.h: seL4_projects_libs/libsel4vm/src/arch/x86/vmcs.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/src/arch/x86/vmexit.h: seL4_projects_libs/libsel4vm/src/arch/x86/vmexit.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/src/arch/x86/vmx_timer.c: seL4_projects_libs/libsel4vm/src/arch/x86/vmx_timer.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/src/arch/x86/i8259/i8259.c: seL4_projects_libs/libsel4vm/src/arch/x86/i8259/i8259.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/src/arch/x86/i8259/i8259.h: seL4_projects_libs/libsel4vm/src/arch/x86/i8259/i8259.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/src/arch/x86/processor/apicdef.h: seL4_projects_libs/libsel4vm/src/arch/x86/processor/apicdef.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/src/arch/x86/processor/cpufeature.h: seL4_projects_libs/libsel4vm/src/arch/x86/processor/cpufeature.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/src/arch/x86/processor/cpuid.c: seL4_projects_libs/libsel4vm/src/arch/x86/processor/cpuid.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/src/arch/x86/processor/cpuid.h: seL4_projects_libs/libsel4vm/src/arch/x86/processor/cpuid.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/src/arch/x86/processor/cr.c: seL4_projects_libs/libsel4vm/src/arch/x86/processor/cr.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/src/arch/x86/processor/decode.c: seL4_projects_libs/libsel4vm/src/arch/x86/processor/decode.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/src/arch/x86/processor/decode.h: seL4_projects_libs/libsel4vm/src/arch/x86/processor/decode.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/src/arch/x86/processor/lapic.c: seL4_projects_libs/libsel4vm/src/arch/x86/processor/lapic.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/src/arch/x86/processor/lapic.h: seL4_projects_libs/libsel4vm/src/arch/x86/processor/lapic.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/src/arch/x86/processor/msr.c: seL4_projects_libs/libsel4vm/src/arch/x86/processor/msr.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/src/arch/x86/processor/msr.h: seL4_projects_libs/libsel4vm/src/arch/x86/processor/msr.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/src/arch/x86/processor/platfeature.h: seL4_projects_libs/libsel4vm/src/arch/x86/processor/platfeature.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/src/sel4_arch/aarch64/arch_fault.h: seL4_projects_libs/libsel4vm/src/sel4_arch/aarch64/arch_fault.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/src/sel4_arch/aarch64/fault.c: seL4_projects_libs/libsel4vm/src/sel4_arch/aarch64/fault.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/src/sel4_arch/arm_hyp/arch_fault.h: seL4_projects_libs/libsel4vm/src/sel4_arch/arm_hyp/arch_fault.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vm/src/sel4_arch/arm_hyp/fault.c: seL4_projects_libs/libsel4vm/src/sel4_arch/arm_hyp/fault.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/CMakeLists.txt: seL4_projects_libs/libsel4vmmplatsupport/CMakeLists.txt: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/README.md: seL4_projects_libs/libsel4vmmplatsupport/README.md: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/arch_include/arm/sel4vmmplatsupport/arch/ac_device.h: seL4_projects_libs/libsel4vmmplatsupport/arch_include/arm/sel4vmmplatsupport/arch/ac_device.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/arch_include/arm/sel4vmmplatsupport/arch/generic_forward_device.h: seL4_projects_libs/libsel4vmmplatsupport/arch_include/arm/sel4vmmplatsupport/arch/generic_forward_device.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/arch_include/arm/sel4vmmplatsupport/arch/guest_boot_init.h: seL4_projects_libs/libsel4vmmplatsupport/arch_include/arm/sel4vmmplatsupport/arch/guest_boot_init.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/arch_include/arm/sel4vmmplatsupport/arch/guest_image_arch.h: seL4_projects_libs/libsel4vmmplatsupport/arch_include/arm/sel4vmmplatsupport/arch/guest_image_arch.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/arch_include/arm/sel4vmmplatsupport/arch/guest_reboot.h: seL4_projects_libs/libsel4vmmplatsupport/arch_include/arm/sel4vmmplatsupport/arch/guest_reboot.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/arch_include/arm/sel4vmmplatsupport/arch/guest_vcpu_fault.h: seL4_projects_libs/libsel4vmmplatsupport/arch_include/arm/sel4vmmplatsupport/arch/guest_vcpu_fault.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/arch_include/arm/sel4vmmplatsupport/arch/guest_vcpu_util.h: seL4_projects_libs/libsel4vmmplatsupport/arch_include/arm/sel4vmmplatsupport/arch/guest_vcpu_util.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/arch_include/arm/sel4vmmplatsupport/arch/irq_defs.h: seL4_projects_libs/libsel4vmmplatsupport/arch_include/arm/sel4vmmplatsupport/arch/irq_defs.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/arch_include/arm/sel4vmmplatsupport/arch/service.h: seL4_projects_libs/libsel4vmmplatsupport/arch_include/arm/sel4vmmplatsupport/arch/service.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/arch_include/arm/sel4vmmplatsupport/arch/vpci.h: seL4_projects_libs/libsel4vmmplatsupport/arch_include/arm/sel4vmmplatsupport/arch/vpci.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/arch_include/arm/sel4vmmplatsupport/arch/vusb.h: seL4_projects_libs/libsel4vmmplatsupport/arch_include/arm/sel4vmmplatsupport/arch/vusb.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/arch_include/x86/sel4vmmplatsupport/arch/acpi.h: seL4_projects_libs/libsel4vmmplatsupport/arch_include/x86/sel4vmmplatsupport/arch/acpi.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/arch_include/x86/sel4vmmplatsupport/arch/e820.h: seL4_projects_libs/libsel4vmmplatsupport/arch_include/x86/sel4vmmplatsupport/arch/e820.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/arch_include/x86/sel4vmmplatsupport/arch/guest_boot_info.h: seL4_projects_libs/libsel4vmmplatsupport/arch_include/x86/sel4vmmplatsupport/arch/guest_boot_info.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/arch_include/x86/sel4vmmplatsupport/arch/guest_boot_init.h: seL4_projects_libs/libsel4vmmplatsupport/arch_include/x86/sel4vmmplatsupport/arch/guest_boot_init.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/arch_include/x86/sel4vmmplatsupport/arch/guest_image_arch.h: seL4_projects_libs/libsel4vmmplatsupport/arch_include/x86/sel4vmmplatsupport/arch/guest_image_arch.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/arch_include/x86/sel4vmmplatsupport/arch/ioport_defs.h: seL4_projects_libs/libsel4vmmplatsupport/arch_include/x86/sel4vmmplatsupport/arch/ioport_defs.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/arch_include/x86/sel4vmmplatsupport/arch/drivers/vmm_pci_helper.h: seL4_projects_libs/libsel4vmmplatsupport/arch_include/x86/sel4vmmplatsupport/arch/drivers/vmm_pci_helper.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/docs/README.md: seL4_projects_libs/libsel4vmmplatsupport/docs/README.md: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/docs/libsel4vmmplatsupport_arm_ac_device.md: seL4_projects_libs/libsel4vmmplatsupport/docs/libsel4vmmplatsupport_arm_ac_device.md: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/docs/libsel4vmmplatsupport_arm_generic_forward_device.md: seL4_projects_libs/libsel4vmmplatsupport/docs/libsel4vmmplatsupport_arm_generic_forward_device.md: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/docs/libsel4vmmplatsupport_arm_guest_boot_init.md: seL4_projects_libs/libsel4vmmplatsupport/docs/libsel4vmmplatsupport_arm_guest_boot_init.md: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/docs/libsel4vmmplatsupport_arm_guest_reboot.md: seL4_projects_libs/libsel4vmmplatsupport/docs/libsel4vmmplatsupport_arm_guest_reboot.md: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/docs/libsel4vmmplatsupport_arm_guest_vcpu_fault.md: seL4_projects_libs/libsel4vmmplatsupport/docs/libsel4vmmplatsupport_arm_guest_vcpu_fault.md: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/docs/libsel4vmmplatsupport_arm_guest_vcpu_util.md: seL4_projects_libs/libsel4vmmplatsupport/docs/libsel4vmmplatsupport_arm_guest_vcpu_util.md: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/docs/libsel4vmmplatsupport_arm_vpci.md: seL4_projects_libs/libsel4vmmplatsupport/docs/libsel4vmmplatsupport_arm_vpci.md: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/docs/libsel4vmmplatsupport_arm_vusb.md: seL4_projects_libs/libsel4vmmplatsupport/docs/libsel4vmmplatsupport_arm_vusb.md: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/docs/libsel4vmmplatsupport_cross_vm_connection.md: seL4_projects_libs/libsel4vmmplatsupport/docs/libsel4vmmplatsupport_cross_vm_connection.md: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/docs/libsel4vmmplatsupport_device.md: seL4_projects_libs/libsel4vmmplatsupport/docs/libsel4vmmplatsupport_device.md: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/docs/libsel4vmmplatsupport_device_utils.md: seL4_projects_libs/libsel4vmmplatsupport/docs/libsel4vmmplatsupport_device_utils.md: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/docs/libsel4vmmplatsupport_guest_image.md: seL4_projects_libs/libsel4vmmplatsupport/docs/libsel4vmmplatsupport_guest_image.md: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/docs/libsel4vmmplatsupport_guest_memory_util.md: seL4_projects_libs/libsel4vmmplatsupport/docs/libsel4vmmplatsupport_guest_memory_util.md: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/docs/libsel4vmmplatsupport_guest_vcpu_util.md: seL4_projects_libs/libsel4vmmplatsupport/docs/libsel4vmmplatsupport_guest_vcpu_util.md: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/docs/libsel4vmmplatsupport_ioports.md: seL4_projects_libs/libsel4vmmplatsupport/docs/libsel4vmmplatsupport_ioports.md: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/docs/libsel4vmmplatsupport_pci.md: seL4_projects_libs/libsel4vmmplatsupport/docs/libsel4vmmplatsupport_pci.md: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/docs/libsel4vmmplatsupport_pci_helper.md: seL4_projects_libs/libsel4vmmplatsupport/docs/libsel4vmmplatsupport_pci_helper.md: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/docs/libsel4vmmplatsupport_virtio_con.md: seL4_projects_libs/libsel4vmmplatsupport/docs/libsel4vmmplatsupport_virtio_con.md: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/docs/libsel4vmmplatsupport_virtio_net.md: seL4_projects_libs/libsel4vmmplatsupport/docs/libsel4vmmplatsupport_virtio_net.md: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/docs/libsel4vmmplatsupport_x86_acpi.md: seL4_projects_libs/libsel4vmmplatsupport/docs/libsel4vmmplatsupport_x86_acpi.md: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/docs/libsel4vmmplatsupport_x86_guest_boot_init.md: seL4_projects_libs/libsel4vmmplatsupport/docs/libsel4vmmplatsupport_x86_guest_boot_init.md: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/docs/libsel4vmmplatsupport_x86_vmm_pci_helper.md: seL4_projects_libs/libsel4vmmplatsupport/docs/libsel4vmmplatsupport_x86_vmm_pci_helper.md: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/include/sel4vmmplatsupport/device.h: seL4_projects_libs/libsel4vmmplatsupport/include/sel4vmmplatsupport/device.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/include/sel4vmmplatsupport/device_utils.h: seL4_projects_libs/libsel4vmmplatsupport/include/sel4vmmplatsupport/device_utils.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/include/sel4vmmplatsupport/guest_image.h: seL4_projects_libs/libsel4vmmplatsupport/include/sel4vmmplatsupport/guest_image.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/include/sel4vmmplatsupport/guest_memory_util.h: seL4_projects_libs/libsel4vmmplatsupport/include/sel4vmmplatsupport/guest_memory_util.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/include/sel4vmmplatsupport/guest_vcpu_util.h: seL4_projects_libs/libsel4vmmplatsupport/include/sel4vmmplatsupport/guest_vcpu_util.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/include/sel4vmmplatsupport/ioports.h: seL4_projects_libs/libsel4vmmplatsupport/include/sel4vmmplatsupport/ioports.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/include/sel4vmmplatsupport/drivers/cross_vm_connection.h: seL4_projects_libs/libsel4vmmplatsupport/include/sel4vmmplatsupport/drivers/cross_vm_connection.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/include/sel4vmmplatsupport/drivers/pci.h: seL4_projects_libs/libsel4vmmplatsupport/include/sel4vmmplatsupport/drivers/pci.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/include/sel4vmmplatsupport/drivers/pci_helper.h: seL4_projects_libs/libsel4vmmplatsupport/include/sel4vmmplatsupport/drivers/pci_helper.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/include/sel4vmmplatsupport/drivers/virtio.h: seL4_projects_libs/libsel4vmmplatsupport/include/sel4vmmplatsupport/drivers/virtio.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/include/sel4vmmplatsupport/drivers/virtio_con.h: seL4_projects_libs/libsel4vmmplatsupport/include/sel4vmmplatsupport/drivers/virtio_con.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/include/sel4vmmplatsupport/drivers/virtio_net.h: seL4_projects_libs/libsel4vmmplatsupport/include/sel4vmmplatsupport/drivers/virtio_net.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/include/sel4vmmplatsupport/drivers/virtio_pci_console.h: seL4_projects_libs/libsel4vmmplatsupport/include/sel4vmmplatsupport/drivers/virtio_pci_console.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/include/sel4vmmplatsupport/drivers/virtio_pci_emul.h: seL4_projects_libs/libsel4vmmplatsupport/include/sel4vmmplatsupport/drivers/virtio_pci_emul.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/plat_include/exynos5/sel4vmmplatsupport/plat/device_map.h: seL4_projects_libs/libsel4vmmplatsupport/plat_include/exynos5/sel4vmmplatsupport/plat/device_map.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/plat_include/exynos5/sel4vmmplatsupport/plat/devices.h: seL4_projects_libs/libsel4vmmplatsupport/plat_include/exynos5/sel4vmmplatsupport/plat/devices.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/plat_include/exynos5/sel4vmmplatsupport/plat/guest_vcpu_util.h: seL4_projects_libs/libsel4vmmplatsupport/plat_include/exynos5/sel4vmmplatsupport/plat/guest_vcpu_util.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/plat_include/exynos5/sel4vmmplatsupport/plat/irq_combiner.h: seL4_projects_libs/libsel4vmmplatsupport/plat_include/exynos5/sel4vmmplatsupport/plat/irq_combiner.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/plat_include/exynos5/sel4vmmplatsupport/plat/vclock.h: seL4_projects_libs/libsel4vmmplatsupport/plat_include/exynos5/sel4vmmplatsupport/plat/vclock.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/plat_include/exynos5/sel4vmmplatsupport/plat/vgpio.h: seL4_projects_libs/libsel4vmmplatsupport/plat_include/exynos5/sel4vmmplatsupport/plat/vgpio.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/plat_include/exynos5/sel4vmmplatsupport/plat/vmct.h: seL4_projects_libs/libsel4vmmplatsupport/plat_include/exynos5/sel4vmmplatsupport/plat/vmct.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/plat_include/exynos5/sel4vmmplatsupport/plat/vpci.h: seL4_projects_libs/libsel4vmmplatsupport/plat_include/exynos5/sel4vmmplatsupport/plat/vpci.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/plat_include/exynos5/sel4vmmplatsupport/plat/vpower.h: seL4_projects_libs/libsel4vmmplatsupport/plat_include/exynos5/sel4vmmplatsupport/plat/vpower.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/plat_include/exynos5/sel4vmmplatsupport/plat/vsdhc.h: seL4_projects_libs/libsel4vmmplatsupport/plat_include/exynos5/sel4vmmplatsupport/plat/vsdhc.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/plat_include/exynos5/sel4vmmplatsupport/plat/vsysreg.h: seL4_projects_libs/libsel4vmmplatsupport/plat_include/exynos5/sel4vmmplatsupport/plat/vsysreg.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/plat_include/exynos5/sel4vmmplatsupport/plat/vuart.h: seL4_projects_libs/libsel4vmmplatsupport/plat_include/exynos5/sel4vmmplatsupport/plat/vuart.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/plat_include/odroidc2/sel4vmmplatsupport/plat/guest_vcpu_util.h: seL4_projects_libs/libsel4vmmplatsupport/plat_include/odroidc2/sel4vmmplatsupport/plat/guest_vcpu_util.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/plat_include/odroidc2/sel4vmmplatsupport/plat/vpci.h: seL4_projects_libs/libsel4vmmplatsupport/plat_include/odroidc2/sel4vmmplatsupport/plat/vpci.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/plat_include/qemu-arm-virt/sel4vmmplatsupport/plat/device_map.h: seL4_projects_libs/libsel4vmmplatsupport/plat_include/qemu-arm-virt/sel4vmmplatsupport/plat/device_map.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/plat_include/qemu-arm-virt/sel4vmmplatsupport/plat/devices.h: seL4_projects_libs/libsel4vmmplatsupport/plat_include/qemu-arm-virt/sel4vmmplatsupport/plat/devices.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/plat_include/qemu-arm-virt/sel4vmmplatsupport/plat/guest_vcpu_util.h: seL4_projects_libs/libsel4vmmplatsupport/plat_include/qemu-arm-virt/sel4vmmplatsupport/plat/guest_vcpu_util.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/plat_include/qemu-arm-virt/sel4vmmplatsupport/plat/vpci.h: seL4_projects_libs/libsel4vmmplatsupport/plat_include/qemu-arm-virt/sel4vmmplatsupport/plat/vpci.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/plat_include/tk1/sel4vmmplatsupport/plat/device_map.h: seL4_projects_libs/libsel4vmmplatsupport/plat_include/tk1/sel4vmmplatsupport/plat/device_map.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/plat_include/tk1/sel4vmmplatsupport/plat/devices.h: seL4_projects_libs/libsel4vmmplatsupport/plat_include/tk1/sel4vmmplatsupport/plat/devices.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/plat_include/tk1/sel4vmmplatsupport/plat/guest_vcpu_util.h: seL4_projects_libs/libsel4vmmplatsupport/plat_include/tk1/sel4vmmplatsupport/plat/guest_vcpu_util.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/plat_include/tk1/sel4vmmplatsupport/plat/usb.h: seL4_projects_libs/libsel4vmmplatsupport/plat_include/tk1/sel4vmmplatsupport/plat/usb.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/plat_include/tk1/sel4vmmplatsupport/plat/vpci.h: seL4_projects_libs/libsel4vmmplatsupport/plat_include/tk1/sel4vmmplatsupport/plat/vpci.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/plat_include/tx1/sel4vmmplatsupport/plat/device_map.h: seL4_projects_libs/libsel4vmmplatsupport/plat_include/tx1/sel4vmmplatsupport/plat/device_map.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/plat_include/tx1/sel4vmmplatsupport/plat/devices.h: seL4_projects_libs/libsel4vmmplatsupport/plat_include/tx1/sel4vmmplatsupport/plat/devices.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/plat_include/tx1/sel4vmmplatsupport/plat/guest_vcpu_util.h: seL4_projects_libs/libsel4vmmplatsupport/plat_include/tx1/sel4vmmplatsupport/plat/guest_vcpu_util.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/plat_include/tx1/sel4vmmplatsupport/plat/vpci.h: seL4_projects_libs/libsel4vmmplatsupport/plat_include/tx1/sel4vmmplatsupport/plat/vpci.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/plat_include/tx2/sel4vmmplatsupport/plat/device_map.h: seL4_projects_libs/libsel4vmmplatsupport/plat_include/tx2/sel4vmmplatsupport/plat/device_map.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/plat_include/tx2/sel4vmmplatsupport/plat/devices.h: seL4_projects_libs/libsel4vmmplatsupport/plat_include/tx2/sel4vmmplatsupport/plat/devices.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/plat_include/tx2/sel4vmmplatsupport/plat/guest_vcpu_util.h: seL4_projects_libs/libsel4vmmplatsupport/plat_include/tx2/sel4vmmplatsupport/plat/guest_vcpu_util.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/plat_include/tx2/sel4vmmplatsupport/plat/vpci.h: seL4_projects_libs/libsel4vmmplatsupport/plat_include/tx2/sel4vmmplatsupport/plat/vpci.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/src/device.c: seL4_projects_libs/libsel4vmmplatsupport/src/device.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/src/device_utils.c: seL4_projects_libs/libsel4vmmplatsupport/src/device_utils.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/src/guest_memory_util.c: seL4_projects_libs/libsel4vmmplatsupport/src/guest_memory_util.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/src/ioports.c: seL4_projects_libs/libsel4vmmplatsupport/src/ioports.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/src/arch/arm/guest_boot_init.c: seL4_projects_libs/libsel4vmmplatsupport/src/arch/arm/guest_boot_init.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/src/arch/arm/guest_image.c: seL4_projects_libs/libsel4vmmplatsupport/src/arch/arm/guest_image.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/src/arch/arm/guest_reboot.c: seL4_projects_libs/libsel4vmmplatsupport/src/arch/arm/guest_reboot.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/src/arch/arm/guest_vcpu_fault.c: seL4_projects_libs/libsel4vmmplatsupport/src/arch/arm/guest_vcpu_fault.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/src/arch/arm/guest_vcpu_util.c: seL4_projects_libs/libsel4vmmplatsupport/src/arch/arm/guest_vcpu_util.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/src/arch/arm/psci.c: seL4_projects_libs/libsel4vmmplatsupport/src/arch/arm/psci.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/src/arch/arm/psci.h: seL4_projects_libs/libsel4vmmplatsupport/src/arch/arm/psci.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/src/arch/arm/service.c: seL4_projects_libs/libsel4vmmplatsupport/src/arch/arm/service.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/src/arch/arm/smc.c: seL4_projects_libs/libsel4vmmplatsupport/src/arch/arm/smc.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/src/arch/arm/smc.h: seL4_projects_libs/libsel4vmmplatsupport/src/arch/arm/smc.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/src/arch/arm/vcpu_fault.h: seL4_projects_libs/libsel4vmmplatsupport/src/arch/arm/vcpu_fault.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/src/arch/arm/devices/ac_device.c: seL4_projects_libs/libsel4vmmplatsupport/src/arch/arm/devices/ac_device.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/src/arch/arm/devices/generic_forward_device.c: seL4_projects_libs/libsel4vmmplatsupport/src/arch/arm/devices/generic_forward_device.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/src/arch/arm/devices/vpci.c: seL4_projects_libs/libsel4vmmplatsupport/src/arch/arm/devices/vpci.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/src/arch/arm/devices/vusb.c: seL4_projects_libs/libsel4vmmplatsupport/src/arch/arm/devices/vusb.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/src/arch/x86/acpi.c: seL4_projects_libs/libsel4vmmplatsupport/src/arch/x86/acpi.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/src/arch/x86/guest_boot_init.c: seL4_projects_libs/libsel4vmmplatsupport/src/arch/x86/guest_boot_init.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/src/arch/x86/guest_image.c: seL4_projects_libs/libsel4vmmplatsupport/src/arch/x86/guest_image.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/src/arch/x86/drivers/vmm_pci_helper.c: seL4_projects_libs/libsel4vmmplatsupport/src/arch/x86/drivers/vmm_pci_helper.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/src/drivers/cross_vm_connection.c: seL4_projects_libs/libsel4vmmplatsupport/src/drivers/cross_vm_connection.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/src/drivers/pci.c: seL4_projects_libs/libsel4vmmplatsupport/src/drivers/pci.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/src/drivers/pci_helper.c: seL4_projects_libs/libsel4vmmplatsupport/src/drivers/pci_helper.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/src/drivers/virtio_con.c: seL4_projects_libs/libsel4vmmplatsupport/src/drivers/virtio_con.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/src/drivers/virtio_console_emul.c: seL4_projects_libs/libsel4vmmplatsupport/src/drivers/virtio_console_emul.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/src/drivers/virtio_emul.c: seL4_projects_libs/libsel4vmmplatsupport/src/drivers/virtio_emul.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/src/drivers/virtio_emul_helpers.c: seL4_projects_libs/libsel4vmmplatsupport/src/drivers/virtio_emul_helpers.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/src/drivers/virtio_emul_helpers.h: seL4_projects_libs/libsel4vmmplatsupport/src/drivers/virtio_emul_helpers.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/src/drivers/virtio_net.c: seL4_projects_libs/libsel4vmmplatsupport/src/drivers/virtio_net.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/src/drivers/virtio_net_emul.c: seL4_projects_libs/libsel4vmmplatsupport/src/drivers/virtio_net_emul.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/src/plat/exynos5/devices/irq_combiner.c: seL4_projects_libs/libsel4vmmplatsupport/src/plat/exynos5/devices/irq_combiner.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/src/plat/exynos5/devices/irq_combiner.h: seL4_projects_libs/libsel4vmmplatsupport/src/plat/exynos5/devices/irq_combiner.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/src/plat/exynos5/devices/misc_devices.c: seL4_projects_libs/libsel4vmmplatsupport/src/plat/exynos5/devices/misc_devices.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/src/plat/exynos5/devices/vclock.c: seL4_projects_libs/libsel4vmmplatsupport/src/plat/exynos5/devices/vclock.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/src/plat/exynos5/devices/vgpio.c: seL4_projects_libs/libsel4vmmplatsupport/src/plat/exynos5/devices/vgpio.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/src/plat/exynos5/devices/vmct.c: seL4_projects_libs/libsel4vmmplatsupport/src/plat/exynos5/devices/vmct.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/src/plat/exynos5/devices/vpower.c: seL4_projects_libs/libsel4vmmplatsupport/src/plat/exynos5/devices/vpower.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/src/plat/exynos5/devices/vsdhc.c: seL4_projects_libs/libsel4vmmplatsupport/src/plat/exynos5/devices/vsdhc.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/src/plat/exynos5/devices/vsysreg.c: seL4_projects_libs/libsel4vmmplatsupport/src/plat/exynos5/devices/vsysreg.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/src/plat/exynos5/devices/vuart.c: seL4_projects_libs/libsel4vmmplatsupport/src/plat/exynos5/devices/vuart.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/src/plat/tk1/devices/misc_devices.c: seL4_projects_libs/libsel4vmmplatsupport/src/plat/tk1/devices/misc_devices.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/src/plat/tk1/devices/usb.c: seL4_projects_libs/libsel4vmmplatsupport/src/plat/tk1/devices/usb.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/src/plat/tk1/devices/vclock.c: seL4_projects_libs/libsel4vmmplatsupport/src/plat/tk1/devices/vclock.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/src/plat/tk1/devices/vuart.c: seL4_projects_libs/libsel4vmmplatsupport/src/plat/tk1/devices/vuart.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/src/sel4_arch/aarch64/guest_boot_sel4arch.h: seL4_projects_libs/libsel4vmmplatsupport/src/sel4_arch/aarch64/guest_boot_sel4arch.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/src/sel4_arch/aarch64/smc.c: seL4_projects_libs/libsel4vmmplatsupport/src/sel4_arch/aarch64/smc.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/src/sel4_arch/aarch64/sysreg_exception.c: seL4_projects_libs/libsel4vmmplatsupport/src/sel4_arch/aarch64/sysreg_exception.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/src/sel4_arch/aarch64/sysreg_exception.h: seL4_projects_libs/libsel4vmmplatsupport/src/sel4_arch/aarch64/sysreg_exception.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/src/sel4_arch/aarch64/vcpu_exceptions.c: seL4_projects_libs/libsel4vmmplatsupport/src/sel4_arch/aarch64/vcpu_exceptions.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/src/sel4_arch/aarch64/vcpu_fault_handlers.h: seL4_projects_libs/libsel4vmmplatsupport/src/sel4_arch/aarch64/vcpu_fault_handlers.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/src/sel4_arch/arm_hyp/guest_boot_sel4arch.h: seL4_projects_libs/libsel4vmmplatsupport/src/sel4_arch/arm_hyp/guest_boot_sel4arch.h: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/src/sel4_arch/arm_hyp/smc.c: seL4_projects_libs/libsel4vmmplatsupport/src/sel4_arch/arm_hyp/smc.c: no owner found
    13-Jan-2021 04:27:15	ERROR:root:seL4_projects_libs/libsel4vmmplatsupport/src/sel4_arch/arm_hyp/vcpu_fault_handlers.h: seL4_projects_libs/libsel4vmmplatsupport/src/sel4_arch/arm_hyp/vcpu_fault_handlers.h: no owner found
    13-Jan-2021 04:27:15	Failing task since return code of [/var/atlassian/application-data/bamboo/temp/CQ-SEL4PROJECTSLIBSCL42-SEL4PROJECTSLIBSLICCQ-1-ScriptBuildTask-3036199863146341194.sh] was 1 while expected 0
    13-Jan-2021 04:27:15	Finished task 'Check license' with result: Failed
    13-Jan-2021 04:27:15	Starting task 'Set permissions so Bamboo can cleanup' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    13-Jan-2021 04:27:15	+ chmod -R o+rwx /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-SEL4PROJECTSLIBSCL42-SEL4PROJECTSLIBSLICCQ
    13-Jan-2021 04:27:15	Finished task 'Set permissions so Bamboo can cleanup' with result: Success
    13-Jan-2021 04:27:15	Running post build plugin 'NCover Results Collector'
    13-Jan-2021 04:27:15	Running post build plugin 'Artifact Copier'
    13-Jan-2021 04:27:15	Running post build plugin 'npm Cache Cleanup'
    13-Jan-2021 04:27:15	Running post build plugin 'Clover Results Collector'
    13-Jan-2021 04:27:15	Running post build plugin 'Docker Container Cleanup'
    13-Jan-2021 04:27:15	Successfully removed working directory at '/var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-SEL4PROJECTSLIBSCL42-SEL4PROJECTSLIBSLICCQ'
    13-Jan-2021 04:27:15	Finalising the build...
    13-Jan-2021 04:27:15	Stopping timer.
    13-Jan-2021 04:27:15	Build CQ-SEL4PROJECTSLIBSCL42-SEL4PROJECTSLIBSLICCQ-1 completed.
    13-Jan-2021 04:27:15	Running on server: post build plugin 'NCover Results Collector'
    13-Jan-2021 04:27:15	Running on server: post build plugin 'Build Hanging Detection Configuration'
    13-Jan-2021 04:27:15	Running on server: post build plugin 'Clover Delta Calculator'
    13-Jan-2021 04:27:15	Running on server: post build plugin 'Maven Dependencies Postprocessor'
    13-Jan-2021 04:27:15	All post build plugins have finished
    13-Jan-2021 04:27:15	Generating build results summary...
    13-Jan-2021 04:27:15	Saving build results to disk...
    13-Jan-2021 04:27:15	Store variable context...
    13-Jan-2021 04:27:15	Indexing build results...
    13-Jan-2021 04:27:15	Finished building CQ-SEL4PROJECTSLIBSCL42-SEL4PROJECTSLIBSLICCQ-1.


This is the most I can report on right now, sorry!

**Comment by oliver-wm** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by maaaat** [comment]
Yay, thanks! :tada:
